### ISSUE TITLE
Metwork doesn't start at boot time

### ISSUE THREAD

**Issue by zgalki** [metwork-framework/mfserv#127]
Hi,
Metwork doesn't start at boot time.

environnement:
Centos7 , multi-user.target
metwork-mfserv V 0.5.6 installed

Here is the result of chkconfig --list command :

metwork         0:arrêt 1:arrêt 2:arrêt 3:arrêt 4:arrêt 5:arrêt 6:arrêt
netconsole      0:arrêt 1:arrêt 2:arrêt 3:arrêt 4:arrêt 5:arrêt 6:arrêt
network         0:arrêt 1:arrêt 2:marche        3:marche        4:marche        5:marche        6:arrêt

**Comment by thefab** [comment]
can't reproduce this
