### ISSUE TITLE
I would like to deploy in parallel 2 versions of the same named mfserv plug-in

### ISSUE THREAD

**Issue by JM-D** [metwork-framework/mfserv#143]
My need is to have 2 versions (online at the same time) of the API we are developing. This use case in order for our client to test, evaluate and make it's choice between the 2 web services made available.

This API is versioned (the version number appears in the URL) and can then be deployed in parallel on our WSO2 API management tool (APIM). Sample: 
`https://api-int.meteofrance.com/ads-cams50/api-nrt/1.2/`

 So I would like to dispose as end-point URL, an URL with the version of the web service (mfserv plugin) but with the same name. Sample:
`http://.../ads-cams50-api-nrt-proto/1.2/`

It is possible to manage a piece of URL within the plug-in but it is not possible to deploy to versions of the same plug-in in the same mfserv server ...

If we have to put the version in the name of the plugin, this will also imply modifications on our git repository since the folder name is the plug-in name ...

So we would like to deploy to versions of the same named plugin in one mfserv instance.
Thank you for your attention.
JM.D

**Comment by thefab** [comment]
the metwork plugin system is built upon rpm packaging system which does not offer this kind of features (https://rpm.org/user_doc/multiple_versions.html)

=> so it won't be implemented in metwork in the short/medium term 

you have to use a different name for each plugin

sorry for that

**Comment by thefab** [comment]
note: the RPM page about this : https://rpm.org/user_doc/multiple_versions.html
