### ISSUE TITLE
permission problem

### ISSUE THREAD

**Issue by mpup371** [metwork-framework/mfserv#264]
after installing metwork-mfserv 0.8:

[mfserv:~/wsbdpe] $ cat  /home/mfserv/tmp/nginx_conf3.20113
nginx: [alert] could not open error log file: open() "/opt/metwork-mfext-0.8/opt/openresty/nginx/logs/error.log" failed (13: Permission denied)

installed as root, run as mfserv:

mfserv:~/wsbdpe] $ ll /opt/metwork-mfext-0.8/opt/openresty/nginx/
total 0
drwxr-xr-x 2 root root 333 22 oct.  14:13 conf
drwxr-xr-x 2 root root  40 22 oct.  14:13 html
drwxr-xr-x 2 root root   6 23 sept. 22:36 logs
drwxr-xr-x 2 root root  19 22 oct.  14:13 sbin

**Comment by thefab** [comment]
This error is not the root cause. 

Because the module completely fails to generate a valid nginx configuration (probably because of a broken plugin), it fails back to the default nginx configuration for error_log (we can't change)
