### ISSUE TITLE
few remarks

### ISSUE THREAD

**Issue by mpup371** [metwork-framework/mfserv#270]
on 0.8:

- bootstrap_plugin.py -h should document the _--template_ option

- the **mediation** template is not documented
- the **empty** template should create the bin directory and documentation indicate the need to put the extra_daemon in it.

**Comment by thefab** [comment]
for the first point `bootstrap_plugin.py create --help` because `--template` is not a general option but an option of the `create` subcommand

**Comment by thefab** [comment]
the mediation template is not documented because it should be dropped in a near future

**Comment by thefab** [comment]
the empty plugin remark is now in #276 
=> I close this issue
