### ISSUE TITLE
yum update

### ISSUE THREAD

**Issue by mpup371** [metwork-framework/mfserv#275]
hi, 
when doing a yum update on my centos7, I have this error:

Transaction check error:
  file /home/mfserv/.bash_profile from install of metwork-mfserv-9:0.9.1-2552.gen.x86_64 conflicts with file from package metwork-mfserv-layer-root-0.8-8:0.8.4-2521.x86_64
  file /home/mfserv/.bashrc from install of metwork-mfserv-9:0.9.1-2552.gen.x86_64 conflicts with file from package metwork-mfserv-layer-root-0.8-8:0.8.4-2521.x86_64

my repo:

[DSI-metwork-stable-centos7]
name=DSI MetWork Stable for CentOS 7
baseurl=http://bathyale.meteo.fr/metwork/stable/centos7
gpgcheck=0
enabled=1
metadata_expire=0

**Comment by thefab** [comment]
the 0.8 => 0.9 hot update is not supported
(but this 0.9 => ... will be supported)

=> please remove 0.8 version and then install 0.9
