### ISSUE TITLE
Mfserv logging in one unique file

### ISSUE THREAD

**Issue by zgalki** [metwork-framework/mfserv#281]
Hi,
Would it be possible to add an option to log all the workers output in one single logging file ?
For debugging purpose on production servers when we should analyse an issue afterwards it would be a great help.

Thanks
Loïc

**Comment by thefab** [comment]
linked to metwork-framework/mfext#571

**Comment by thefab** [comment]
I close this because the corresponding work is now listed in https://github.com/metwork-framework/resources/issues/47
