### ISSUE TITLE
Possible wrong use of the word "eventually" in mfserv logs

### ISSUE THREAD

**Issue by zgalki** [metwork-framework/mfserv#282]
Hi,
Does the use of "eventually" in these files meant to be "possibly, potentially" or "finally" ?
```
bin/mfserv.init:echo -n "- Eventually stopping ${MODULE_LOWERCASE} module..."
opt/python3/lib/python3.5/site-packages/gunicorn/six.py:        self.__get_module(fullname)  # eventually raises ImportError
share/bash_profile:# We eventually override with custom module wide settings
share/bashrc:# We eventually override with system wide custom settings
share/bashrc:# We eventually override with module wide custom settings
```

As I understand it when it appears it seems to mean "possibly" not "finally"

**Comment by thebaptiste** [comment]
It means "possibly", we should change it. You are right, "eventually" is a "false friend" in french, it looks like "éventuellement", french word for "possibly", but it means "finally"...

**Comment by thebaptiste** [comment]
Note : for six.py, it's not Metwork code (we only build the package), so we won't change any comment in this code.

**Comment by thebaptiste** [comment]
Closed by [](https://github.com/metwork-framework/mfext/pull/574)
