### ISSUE TITLE
HTTP 502 Metwork response when the workers are restarted by max_age feature

### ISSUE THREAD

**Issue by zgalki** [metwork-framework/mfserv#286]
Hi,

If we request a plugin during the workers (I have 8 workers set) restart, metwork sends back a HTTP 502 error. It is the same error we can have during the mfserv module starting process.

Loïc

**Comment by thefab** [comment]
important: during an automatic max_age restart

**Comment by thefab** [comment]
juste released the fix in 0.9 branch: https://medium.com/metwork-framework/updates-of-the-0-9-branch-75b134305dcb
