### ISSUE TITLE
Make release fails with no url in config.ini

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfserv#325]
Execution of command "make release" ends with below error if an url is not set in config.ini file: 

"===== BASH STDERR ========================
error: line 7: Empty tag: URL:
make: * [release] Error 1"

**Comment by thebaptiste** [comment]
This behaviour occurs for url but also for other tags such as vendor, license, etc... If the line is removed it doesn't work either (with another error message).

For some Metwork internal reasons, we must keep the url line present and not empty in config.ini.
By default, when bootstraping a plugin template, the line is present with a default irrelevant value, so the problem occurs if you change it to empty value or remove the line.

For the next version, the error messages will be more explicit  : 
- if the url line is present but not set to some(even irrelevant) value : 
"url must not be left empty, please fix it in config.ini"
- if the url line is completely missing : 
"url tag is mandatory, please add the 'url: ' line in config.ini"

We will also add a commentary in config.ini to indicate not to left url value empty nor suppress the url line. 

All this for url but also for the other concerned tags.
