### ISSUE TITLE
Creating a plugin with templates of type aiohttp,  doesn't not create the python3_virtualenv_sources

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfserv#342]
Hi,

When I create a plugin with template as described in [MFSERV aiohttp python plugin](http://metwork-framework.org/pub/metwork/releases/docs/stable/mfserv/mfserv_tutorials.html#aiohttp-python-plugin) the `python3_virtualenv_sources` directory containing `requirements-to-freeze.txt` is not created by the `bootstrap_plugin.py` (unlike the other template types)

I have to create it by myself.

Not really a bug (?). But you have to know if you are a beginner

PS: I am using Metwork V0.9

**Comment by thebaptiste** [comment]
I confirm this is the behavior with Metwork 0.9
The problem is solved with Metwork 1.0 : there is a specific template for aiohttp : 
`bootstrap_plugin.py create --template=python3_aiohttp my_plugin`
and the `python3_virtualenv_sources` directory is created
