### ISSUE TITLE
Upgrade aiohttp python package

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfserv#381]
Currently, MFSERV use aiohttp v 3.4.4.
It would be nice (if possible) to upgrade to the lastest stable version (v 3.6.2) with some issues fixed.

Thanks

**Comment by thebaptiste** [comment]
Until release 0.9, aiohttp was included in mfserv with release 3.4.4
With release 1.0, aiohttp is now included in mfext with release 3.6.2 (and can be used in mfserv)
The only thing you have to do is to upgrade Metwork to release 1.0
