### ISSUE TITLE
Post request for MapServer

### ISSUE THREAD

**Issue by laurentmarty** [metwork-framework/mfserv#382]
Bonjour,

OGC WFS requests are made through MetWorks to MapServer. Currently only passing parameters via the GET verb, is possible. Normally MapServer accepts the POST verb. Is it possible to have both verbs?

Laurent

**Comment by thefab** [comment]
we use mapserver as a library through a function exposed in the mapserver C code
(this function does not support POST requests => we need a dev in mapserver code, sorry we can't do anything easily)
