### ISSUE TITLE
Add ngx_http_auth_request_module to nginx

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfserv#383]
We need to use ngx_http_auth_request_module (http://nginx.org/en/docs/http/ngx_http_auth_request_module.html).

It seems nginx provided by Metwork does not have this module.

This module is not built by default, it should be enabled with the `--with-http_auth_request`_module configuration parameter.

Currently, we use **Metwork 0.9**.

Could you enable this module in nginx  (**Metwork 0.9** and >)?

Thanks.

**Comment by thefab** [comment]
@thebaptiste if you are back, can you add this in the openresty build process? thanks

**Comment by thebaptiste** [comment]
Done and backported in release 0.9 (a new release of mfext 0.9 is available including this fix).

**Comment by thebaptiste** [comment]
https://medium.com/metwork-framework/mfext-0-9-10-71fab4728958?sk=eb457533d858cac6f8809018747e9968

**Comment by dearith** [comment]
It works !!! Thanks a lot 👍
