### ISSUE TITLE
Config.ini - Wrong comment for [custom]  configuration (in MSERV plugin templates ?)

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfserv#433]
When I create a plugin with a template (e.g. python_flask), a config.ini is generated : it's OK.

But in the comment generated in the custom section is not correct:

```
# Here is a space for your public configuration keys
#   (ie. overridable by administrator after deployment)
# Your keys shouldn't start with an underscore (as they are public)
#   and you have to read their value through the corresponding env variable
#   and NOT by parsing this file
# A key named "foo_bar" here will generate (in plugin_env) an env var called
# MFSERV_PLUGIN_{YOU PLUGIN NAME IN UPPER CASE}_CUSTOM_{YOUR KEY IN UPPERCASE}
# with the corresponding value inside
```

The correct env var is MFSERV_CURRENT_PLUGIN_CUSTOM_{YOUR KEY IN UPPERCASE} as mentionned in the MetWork  plugins guide documentation (http://metwork-framework.org/pub/metwork/releases/docs/release_1.0/mfserv/350-plugin_guide/#215-defining-configuration-options).

Not a very important issue, but i got caught myself, by reading only the config.ini comment

**Comment by thefab** [comment]
thanks @dearith, PR made 
I completed the comment for mfdata also
