### ISSUE TITLE
Django >= 3.1 - "import os" error while running postinstall

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfserv#527]
Django as replaced -in its default setting file- 
`import os`
by
`from pathlib import Path`

From **Django version 3.1**.
Source: https://github.com/django/django/blob/main/django/conf/project_template/project_name/settings.py-tpl

File `mfserv/adm/templates/plugins/python3_django/{{cookiecutter.name}}/postinstall` must be fixed to take into account both/either **Path** (django >=3.1) and **os** (django <=3.1)
Code involved : `STATIC_ROOT = os.path.join(BASE_DIR, "{{cookiecutter.name}}/static")`

**Comment by thebaptiste** [comment]
Closed by #529
