### ISSUE TITLE
getcap 2.48-2.el8 --> "Checking nginx generation" HAS FAILED

### ISSUE THREAD

**Issue by florianwns** [metwork-framework/mfserv#534]
Hello team, 

On my CentOs 8 version, I needed to reinstall an old version of libcap because getcap version 2.48 seems to change its display.
I don't know why, but getcap output changes depending on getcap versions:

_with v2.48_
> /opt/metwork-mfext-1.2/opt/openresty/nginx/sbin/nginx cap_net_bind_service=ep

_previously with v2.26_
> /opt/metwork-mfext-1.2/opt/openresty/nginx/sbin/nginx=cap_net_bind_service+ep

So it's not a problem, but it's just to warn your team that it might be a problem later.

Thx for your reading.

**Comment by florianwns** [comment]
Also since this commit and the getcap checking, the version v2.48 of getcap fail the test.

https://github.com/metwork-framework/mfserv/commit/9e2186ef5a50823134016bf17969489b0a227ab5

**Comment by thebaptiste** [comment]
Interesting information for the future but... where did you get `libcap 2.48` ?
(the version provided with CentOS 8 seems to be 2.26)

**Comment by florianwns** [comment]
It was due to a migration from CentOS-Linux to CentOS-Stream, i think.
