### ISSUE TITLE
Error in layer dependencies for nodejs template

### ISSUE THREAD

**Issue by ne0t3ric** [metwork-framework/mfserv#541]
## The problem

When bootstrapping a node plugin, there is an error when trying to dev_link the plugin.

```
[INFO]: layer plugin_alim-ui@mfserv[/home/mfdata-remote/mfserv/alim-ui] depends on a not installed layer nodejs@mfserv => we can't load it
[WARNING]: impossible to load the layer: plugin_alim-ui@mfserv
[WARNING]: don't launch the command because of at least one layer loading fail
```

## Analysis
When bootstraping the plugin, we are invited to install `metwork-mfext-layer-nodejs` `mfext` extra layer. ( see [https://github.com/metwork-framework/mfserv/blob/master/adm/templates/plugins/node/README.md](node plugin README) )

But in plugin folder, .layerapi2_dependencies uses nodejs@mfserv

## Step to reproduce

```
bootstrap_plugin.py create --template=node my_node_app

cd my_node_app/

make develop
```

## Solution

In generated .layerapi2_dependencies (see https://github.com/metwork-framework/mfserv/blob/master/adm/templates/plugins/_common/node_layerapi2_dependencies) :
replace `nodejs@mfserv` with `nodejs@mfext`

**Comment by thebaptiste** [comment]
Thanks, we will fix it... at our return from holiday !
When you have the fix to solve an issue, don't hesitate to do a pull request (on integration branch)
