### ISSUE TITLE
template python3_django3 - rename and upgrade to Django 4.2 LTS

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfserv#611]
Django 3.2 is soon deprecated. The LTS version is now Django 4.2. See https://www.djangoproject.com/download/

I think it's not a good idea to "lock" the django version into the name of the mfserv template. So:

- rename template from "python3_django3" to **python3_django**
- upgrade `requirements-to-freeze.txt` from "django>=3.2.17,<4.0" to **django>=4.2.7,<5.0** (or **django>=4.2.7** only ?)
- remove deprecated "url" from `postinstall` script

**Comment by thebaptiste** [comment]
Agree to the proposed changes.
I let you choose between the two options for `requirements-to-freeze.txt`.
I suppose you did check that the plugin is working with Django 4 ?
