### ISSUE TITLE
warning in nginx logs

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfserv#72]
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /home/mfserv/tmp/config_auto/nginx.conf:68
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /home/mfserv/tmp/config_auto/nginx.conf:75

**Comment by thebaptiste** [comment]
It seems I don't have this issue on my computer...
On internet you can find several posts suggesting the correct syntax should be "127.0.0.0/24" (for example [this one](https://serverfault.com/questions/577317/what-does-low-address-bits-are-meaningless-mean/577321))
